In [2]:
import numpy as np 
import pandas as pd

In [3]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [4]:
train.head()

month  year    ID  tempmax  tempmin  temp   dew  humidity  windgust  \
0     11  2022  1323     79.9     50.1  65.3  41.5      46.2      18.6   
1     12  2022  1362     89.6     50.1  71.6  50.1      50.6      11.2   
2      3  2022  1079     95.1     69.9  81.9  44.3      30.1      19.7   
3      5  2022  1148     93.3     72.6  81.7  66.2      61.8      27.1   
4     11  2023  1694     85.4     67.4  73.5  62.9      71.2      18.8   

   windspeed  winddir  sealevelpressure  cloudcover  visibility  \
0       13.9     81.0            1014.2         4.9         9.3   
1       10.3    285.4            1018.2         4.3         7.1   
2        9.2    308.5            1009.9        61.7         6.5   
3       20.8    264.7            1007.7        19.6         7.8   
4       15.2    158.2            1012.0        70.9        10.2   

   solarradiation  solarenergy  weather-condition  
0           230.0         19.9          clear-day  
1           214.8         18.7          clear-day  
2           240.5         20.8  partly-cloudy-day  
3           315.2         27.3          clear-day  
4           139.4         12.1               rain

In [5]:
test.head()

month  year    ID  tempmax  tempmin  temp   dew  humidity  windgust  \
0      5  2022  1137    100.5     71.5  85.3  61.1      50.5      17.4   
1      7  2022  1198     75.3     70.1  73.2  71.6      94.9      25.7   
2      1  2024  1739     86.1     65.6  74.1  58.0      59.6      15.0   
3      8  2023  1583     80.7     70.4  74.4  69.5      85.1      33.8   
4     10  2023  1655     87.2     71.0  77.9  62.5      60.7      15.4   

   windspeed  winddir  sealevelpressure  cloudcover  visibility  \
0       13.9    276.5            1006.1        18.6         6.4   
1       16.1    259.9            1006.3        98.3         4.1   
2        9.4     78.2            1015.1        18.0        10.8   
3       23.5    257.2            1005.5        88.1        11.4   
4       10.5     25.1            1013.2        46.9        11.9   

   solarradiation  solarenergy  
0           316.5         27.2  
1            23.7          2.0  
2           208.7         18.1  
3           204.2         17.7  
4           200.3         17.3

In [6]:
test1 = test['ID'].values
test.drop(columns=['ID'], inplace=True)

In [7]:
test.isnull().sum()

month               0
year                0
tempmax             0
tempmin             0
temp                0
dew                 0
humidity            0
windgust            2
windspeed           0
winddir             0
sealevelpressure    0
cloudcover          0
visibility          0
solarradiation      0
solarenergy         0
dtype: int64

In [8]:
train.isnull().sum()


month                0
year                 0
ID                   0
tempmax              0
tempmin              0
temp                 0
dew                  0
humidity             0
windgust             7
windspeed            0
winddir              0
sealevelpressure     0
cloudcover           0
visibility           0
solarradiation       0
solarenergy          0
weather-condition    0
dtype: int64

In [9]:
train.shape

(634, 17)

In [10]:
train = train.dropna()

In [11]:
train.isnull().sum()

month                0
year                 0
ID                   0
tempmax              0
tempmin              0
temp                 0
dew                  0
humidity             0
windgust             0
windspeed            0
winddir              0
sealevelpressure     0
cloudcover           0
visibility           0
solarradiation       0
solarenergy          0
weather-condition    0
dtype: int64

In [12]:
train.shape

(627, 17)

In [13]:
train.dtypes

month                  int64
year                   int64
ID                     int64
tempmax              float64
tempmin              float64
temp                 float64
dew                  float64
humidity             float64
windgust             float64
windspeed            float64
winddir              float64
sealevelpressure     float64
cloudcover           float64
visibility           float64
solarradiation       float64
solarenergy          float64
weather-condition     object
dtype: object

In [14]:
train['weather-condition'].unique()

array(['clear-day', 'partly-cloudy-day', 'rain'], dtype=object)

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
ohe =  OneHotEncoder()

In [17]:
target = ohe.fit_transform(train[['weather-condition']])

In [18]:
target = target.toarray()
print(target)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [19]:
from sklearn.linear_model import Ridge

In [20]:
main_col = ["month","year","tempmax","tempmin","temp","dew","humidity","windgust","windspeed","winddir","sealevelpressure","cloudcover","visibility","solarradiation","solarenergy"]

In [21]:
from sklearn.neighbors import LocalOutlierFactor


lof = LocalOutlierFactor()


outliers = lof.fit_predict(train[main_col])

In [22]:
outliers

array([ 1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [25]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='most_frequent') 


imputer.fit(train[main_col])


X_train_imputed = imputer.transform(train[main_col])
X_test_imputed = imputer.transform(test)

In [26]:
rig = Ridge(alpha = .1)

In [27]:
rig.fit(X_train_imputed, target)

Ridge(alpha=0.1)

In [28]:
predictions = rig.predict(X_test_imputed)

In [29]:
print(predictions)

[[ 5.56940256e-01  2.07001345e-01  2.36058399e-01]
 [-2.39678529e-02 -1.78249555e-01  1.20221741e+00]
 [ 5.52945527e-01  2.11353308e-01  2.35701165e-01]
 [-1.32152517e-01  1.98550833e-01  9.33601684e-01]
 [ 4.96142504e-02  5.76560751e-01  3.73824998e-01]
 [ 6.11126281e-01  3.27491984e-01  6.13817351e-02]
 [ 4.95310008e-01 -1.96251241e-01  7.00941232e-01]
 [ 7.20799995e-01  3.03227925e-02  2.48877213e-01]
 [-3.27280639e-01  1.03589681e+00  2.91383831e-01]
 [ 4.41730778e-01  5.38277159e-01  1.99920625e-02]
 [ 5.02657366e-01  3.69188134e-01  1.28154500e-01]
 [ 2.64639035e-02  1.15062838e-01  8.58473259e-01]
 [ 5.90064408e-01  1.34507662e-01  2.75427930e-01]
 [-3.75042356e-01  9.28696589e-01  4.46345767e-01]
 [ 5.76604059e-01  4.40662967e-01 -1.72670257e-02]
 [ 6.05027759e-01  2.27412087e-01  1.67560154e-01]
 [ 1.79578978e-01  4.62316624e-02  7.74189360e-01]
 [ 5.33328986e-01  2.08905937e-01  2.57765077e-01]
 [ 5.70236575e-01  4.32822347e-01 -3.05892176e-03]
 [ 2.78499394e-01  2.96504598e-

In [30]:
from numpy import argmax

In [31]:
result = argmax(predictions)

In [32]:
result = []

In [33]:
for i in predictions:
    result.append(argmax(i))

In [34]:
print(result)

[0, 2, 0, 2, 1, 0, 2, 0, 1, 1, 0, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 1, 0, 2, 0, 0, 1, 2, 1, 0, 2, 0, 1, 0, 1, 0, 2, 0, 2, 2, 1, 2, 1, 0, 1, 0, 0, 2, 0, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 1, 0, 2, 2, 0, 2, 2, 0, 2, 1, 0, 1, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 1, 1, 0, 0, 2, 1, 1, 0, 2, 1, 0, 0, 2, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 2, 0, 1, 0, 0, 0, 2, 2, 1, 0, 2, 2, 1, 2, 0, 2, 0, 0]


In [35]:

weather_pred = []
for i in result:
    if i == 0:
        weather_pred.append("clear-day")
    elif i == 1:
        weather_pred.append("partly-cloudy-day")
    else:
        weather_pred.append("rain")

In [36]:
print(weather_pred)

['clear-day', 'rain', 'clear-day', 'rain', 'partly-cloudy-day', 'clear-day', 'rain', 'clear-day', 'partly-cloudy-day', 'partly-cloudy-day', 'clear-day', 'rain', 'clear-day', 'partly-cloudy-day', 'clear-day', 'clear-day', 'rain', 'clear-day', 'clear-day', 'rain', 'rain', 'clear-day', 'partly-cloudy-day', 'rain', 'clear-day', 'clear-day', 'rain', 'rain', 'rain', 'rain', 'rain', 'rain', 'rain', 'rain', 'clear-day', 'clear-day', 'rain', 'clear-day', 'rain', 'clear-day', 'clear-day', 'partly-cloudy-day', 'clear-day', 'rain', 'clear-day', 'clear-day', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'clear-day', 'rain', 'clear-day', 'partly-cloudy-day', 'clear-day', 'partly-cloudy-day', 'clear-day', 'rain', 'clear-day', 'rain', 'rain', 'partly-cloudy-day', 'rain', 'partly-cloudy-day', 'clear-day', 'partly-cloudy-day', 'clear-day', 'clear-day', 'rain', 'clear-day', 'partly-cloudy-day', 'rain', 'clear-day', 'clear-day', 'rain', 'clear-day', 'clear-day', 'clear-day', 'clear-day', 'clear-day', 

In [37]:
test = pd.read_csv("test.csv")

In [38]:
print(len(test1))
print(len(weather_pred))

test1 = np.array(test1)
weather_pred = np.array(weather_pred)

print(type(test1))
print(type(weather_pred))


159
159
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [39]:
final = pd.DataFrame({'ID': test1,'weather-condition':weather_pred})

In [40]:
final.head(5)

ID  weather-condition
0  1137          clear-day
1  1198               rain
2  1739          clear-day
3  1583               rain
4  1655  partly-cloudy-day

In [41]:
final.to_csv("submission.csv", index = False)